#! bash -uvx
branch=`git rev-parse --abbrev-ref HEAD`
git tag -l | xargs -n 1 git push --delete origin
git tag | xargs git tag -d
git checkout --orphan latest_branch
git add -A
git commit -am "Initial commit"
git branch -D $branch
git branch -m $branch
git push -f origin $branch
git push --set-upstream origin $branch
